### ISSUE TITLE
Ignores step in bootstrap modal

### ISSUE THREAD

**Issue by Bezmundo** [benmarch/angular-bootstrap-tour#10]
When I have a step inside a modal it seems to skip this step and continues to the next step on the page. I have the bootstrap opened via a jquery call. However if you have the modal opened before the tour start then it continues that step. 

I've tried delaying the on-next function while the modal opens but that doesn't seem to work, any ideas?

**Comment by benmarch** [comment]
Hmm, try wrapping your modal open call in a [$scope.$apply()](https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$apply) function. My guess is that it gets skipped because the tour step is hidden when it is supposed to show.

**Comment by Bezmundo** [comment]
I've tried that with no success. If you have a step two tour with one on the main body and then have another step in a modal, the next button isn't an option. It doesn't seem to see the next step at all if its in a modal. Also if there's another step after the modal it just skips straight to that.

I've looked at the tour in console log and it does display the modal steps but just completely ignores them when navigating through the tour

**Comment by benmarch** [comment]
Ah ok, try adding skip="false" to the modal step, this should force it not to skip.

**Comment by Bezmundo** [comment]
Was about to try that but just noticed its not actually displaying the modal step in the array.

**Comment by benmarch** [comment]
Yeah it reevaluates the steps every time a step is displayed and regenerates the array. Is the modal step in the DOM before it's displayed or is it added dynamically? If it's in the DOM then it should still let the controller know that it shouldn't be skipped.

**Comment by Bezmundo** [comment]
No its not added dynamically and it is in the html markup. Its just ignoring it completely. I will try and make an example now so you can see it in action

**Comment by Bezmundo** [comment]
http://codepen.io/anon/pen/bNjGav   heres an example

**Comment by benmarch** [comment]
Ah ok thank you for the example, I see the problem. Should be a quick fix, I will have it ready in the next couple days.

**Comment by benmarch** [comment]
Ok it should be working now in version 0.3.1. I forked your example to show how it works: http://codepen.io/anon/pen/wBxXwV

Just use the availableWhenHidden="true" option and use onShow and onHide to open and close the modal. Let me know how it goes!
