### ISSUE TITLE
Rename `stepId` to `id`

### ISSUE THREAD

**Issue by korya** [benmarch/angular-bootstrap-tour#16]
Currently, the value of `tour-step` attribute is assigned to `step.stepId` (https://github.com/benmarch/angular-bootstrap-tour/blob/ff18966e4ede35f952517fee34f7dd73afa7a467/app/tour_step_directive.js#L18). As far as I understand this `stepId` property is used internally to identify steps (https://github.com/benmarch/angular-bootstrap-tour/blob/e1f6134598c1324c3149b52f99b80f131c2cd8cd/app/tour_controller.js#L101).

According to https://github.com/sorich87/bootstrap-tour/pull/44 the original bootstrap-tour defines `step.id` to identify the steps. In addition it set the id attribute of popover window to the same value.

IMHO, it makes sense to stay aligned/consistent with bootstrap-tour and  rename `stepId` to `id`.

**Comment by benmarch** [comment]
Yeah I'm not sure why I went with stepId over id, it's not my usual style. My guess is that I was trying to avoid collisions with the original plugin. Would you mind making the change and creating a pull request?

**Comment by benmarch** [comment]
I am going to leave it the way it is since I don't want there to be any issues; step.id is for Bootstrap Tour, step.stepId is for Angular Bootstrap Tour. Since it isn't public API then I don't think it is worth refactoring.
