### ISSUE TITLE
Tour Element is not generated when starting the tour on click

### ISSUE THREAD

**Issue by TineBepunkt** [benmarch/angular-bootstrap-tour#18]
When starting the tour by clicking on a button, there is a tour and a tour step object, but the markup for it is not generated on the page, thus I don't see any popovers. Does anybody had the same troubles and could help?

**Comment by benmarch** [comment]
Can you post the relevant markup and JS code? If that all looks good then the issue could be with BST instead of the angular code around it. There are some quirks around scopes with this component though, so that could be the issue.

**Comment by benmarch** [comment]
No response from OP, closing...
