### ISSUE TITLE
Backdrop is not working

### ISSUE THREAD

**Issue by erickne** [benmarch/angular-bootstrap-tour#21]
Already added bakdrop configuration, but it's not working.

    TourConfigProvider.set('backdrop',true);

**Comment by benmarch** [comment]
I probably should have named the provider slightly differently; it's not actually for configuring the Tour object, it's for configuring this plugin. To get the backdrop working just specify it on the tour element:
```html
<div bs-tour backdrop="true">...</div>
```

**Comment by erickne** [comment]
Worked, Thank! Keep up the good job!
