### ISSUE TITLE
Scope tour does not bind to controller as syntax

### ISSUE THREAD

**Issue by NetanelBasal** [benmarch/angular-bootstrap-tour#22]
I cant bind tour to my controller i get undefined. why this is happen?

```javascript
class FeedController {

  constructor( $scope ) {
    $scope.$watch('tour', function( newVal, oldVal ) {
      console.log(newVal, oldVal); // is undefined
    });
  }
}
```

```html
  <div class="row" tour orphan="true" storage="false">
 </div>

```

**Comment by NetanelBasal** [comment]
I removed from the tour directive the scope: true, and it works, you have an idea why?

**Comment by benmarch** [comment]
If the FeedController is outside the tour in the DOM then this would be caused by "scope: true" creating an inherited scope from FeedController (FeedController -> Tour). So when you try to access the tour property it's actually defined on the inner scope so you cant see it from the FeedController scope. If FeedController is inside then I would have to investigate a little more. Try moving FeedController to the inside if it isn't already. 

Btw I like the use of ES6, i haven't had the time to play around much with it yet.

**Comment by NetanelBasal** [comment]
The tour directive is inside the feed controller and only when i removed
the scope true its working.

**Comment by benmarch** [comment]
Sorry typo, try moving it to the *outside*, it won't require you to remove scope: true.

**Comment by NetanelBasal** [comment]
I will try and let you know thanks.

**Comment by benmarch** [comment]
Cool. Actually that wasnt a typo (I'm a bit distracted atm) the FeedController should be inside the tour if possible.

**Comment by NetanelBasal** [comment]
When i did this like you say:

```html
<div tour orphan="true" storage="false" on-end="feed.onTourEnd(tour)">
  <div ng-controller="FeedController as feed">
  </div>
</div>

```

It is works but i get this error now:
$element.popover is not a function

**Comment by benmarch** [comment]
`<div tour orphan="true" storage="false" on-end="feed.onTourEnd(tour)">`

`feed` won't be defined here. Not sure if that is causing the problem, but it might be related. I recommend creating a controller for your tour ("MyTourController") and you can register the event handlers in there:

```javascript
<div ng-controller="MyTourController as tourCtrl">
  <div tour orphan="true" storage="false" on-end="tourCtrl.onTourEnd(tour)">
    <div ng-controller="FeedController as feed">
    </div>
  </div>
</div>
```
You might even be able to put the ng-controller on the tour div so you don't have to create more markup.

**Comment by NetanelBasal** [comment]
Ok i will try now thanks

**Comment by NetanelBasal** [comment]
Cool all works well, my problem was that i does not include the bootstrap js and i added the standalone version and your suggestion fixed the first issue, thanks a lot for your help!
