### ISSUE TITLE
Ending opened tour when i switch page/redirection

### ISSUE THREAD

**Issue by Dioude** [benmarch/angular-bootstrap-tour#28]
Hello,
i'm having a small problem, i have set my tour to start automatically when i enter a certain page/controller, but when i go to another page/controller with the tour opened, it doesn't close. And i can't close it manually anymore.

Maybe i've set it all wrong from the begining, i got a hidden button with ng-click="tour.restart(true)" which is clicked in my controller.

How can i make it close itself on page switching ?

**Comment by benmarch** [comment]
Hey @Dioude sorry for the delayed response... in the controller that automatically opens the tour, try adding the following snippet (will depend on how you are actually navigating):

    $scope.$on('$destroy', function () {
        $scope.tour.end();
    });

If that doesn't do it, please explain how you have set up your navigation and I can try to assist further.

**Comment by benmarch** [comment]
Any update @Dioude?

**Comment by Dioude** [comment]
it works like a charm, thanks !
