### ISSUE TITLE
Step config only through directives ?

### ISSUE THREAD

**Issue by bixibu** [benmarch/angular-bootstrap-tour#3]
Hi

Is there a possible way to handle steps tour with JS instead of directives ? Like the standard bootstrap-tour ? :
```
var tour = new Tour(
  steps: [
  {
    element: "#my-element",
    title: "Title of my step",
    content: "Content of my step"
  },
  {
    element: "#my-other-element",
    title: "Title of my step",
    content: "Content of my step"
  }
]);
```

In my module-driven angular app, adding directives all over my templates is not an option . I need a dedicated and separated module for that.

Thanks for this module anyway

**Comment by benmarch** [comment]
I don't think this use case fits the plugin. Closing.

**Comment by maximelebreton** [comment]
+1
or add ```true``` and ```false``` argument to enable/disable the ```tour-step``` directive, because in a **```ng-repeat```** there is no simple ways to add a conditional step...
The only ways are:
- a js declaration based on a class like the @jscti example
- or a ```ng-attr-tour-step="condition ? true : false"```

**Comment by benmarch** [comment]
@maximelebreton you can use the "skip" attribute to enable/disable a tour step:
    
    <div tour-step skip="conditional">...</div>

The conditional will be tested on every digest, and the "Previous" and "Next" buttons are smart enough to know what the next enabled step should be.

**Comment by maximelebreton** [comment]
great!
i can't find this suggestion in the readme, can you update it?

thanks @benmarch, and great job!

**Comment by benmarch** [comment]
It's under the TourStep Directive section: https://github.com/benmarch/angular-bootstrap-tour#tourstep-directive. Good luck!
