### ISSUE TITLE
grunt error

### ISSUE THREAD

**Issue by fpernia** [benmarch/angular-bootstrap-tour#30]
When I try to execute the project with the instructions of MD file, specifically when I execute "grunt" I get this error:

Running "jshint:all" (jshint) task

   Gruntfile.js
     99 |        bower_main: {
         ^ Identifier 'bower_main' is not in camel case.
   app\tour_controller.js
    118 |            tour = new Tour(options);
                                ^ 'Tour' is not defined.

>> 2 errors in 8 files
Warning: Task "jshint:all" failed. Use --force to continue.

Aborted due to warnings.

**Comment by fpernia** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/12814610/10288000/1529fd48-6b60-11e5-9ccd-cb32012289dd.png)

**Comment by benmarch** [comment]
Good catch, I'll be able to fix that pretty quickly this evening. Thanks!

**Comment by fpernia** [comment]
@benmarch Thanks for your time. I'll be aware :)

**Comment by pgksunilkumar** [comment]
When I Try to execute the Bootstrap Tour in grunt i am getting this error Please Help Me out with this Solution

![image](https://user-images.githubusercontent.com/11393456/35568976-c3c943b8-05f0-11e8-8940-7122ff527af4.png)

**Comment by pgksunilkumar** [comment]
When I add the window.Tour() its working fine this is the correct solution..?

```
var tour = new  Window.Tour({
--
});
```

**Comment by benmarch** [comment]
@pgksunilkumar are you running Grunt in your app, or in the Angular Bootstrap Tour source code?

**Comment by pgksunilkumar** [comment]
Yes I am using the Grunt App

**Comment by benmarch** [comment]
Ok this appears to be an issue with _your_ JSHint config then. It also looks like you are bypassing this library and trying to use Bootstrap Tour directly. Please see the README for examples.
