### ISSUE TITLE
Call tour.start() from controller

### ISSUE THREAD

**Issue by vvillasoto** [benmarch/angular-bootstrap-tour#36]
The tour is not initializing automatically by itself even with *storage="false"*. And I do not want the tour to start from a button's *ng-click* function, but I would like it to be called immediately from within my controller.

I want to call **tour.start() from within my module controller** inside an init() function called every 60 seconds. 
```javascript
$scope.initTour = function() {
    $scope.tour.start();  <!-- insert code to call here -->
}

$scope.init = function() {
    MyService.getData().then(
        function(data) {
              $scope.data = data;
              $timeout($scope.initTour(), 2000);
        }
}

var interval = $interval($scope.init, 60000);

$scope.$on('$destroy', function() {
      $interval.cancel(interval);
});
```
But I cant get it to work. 

Any help would be appreciated.

Thanks

**Comment by benmarch** [comment]
Check to see if $scope.tour is available, if your controller is declared outside of the tour declaration then it will not be available. In the initTour function wrap everything with `if ($scope.tour) { ... }`.

If that isn't the issue, try using `tour.restart(true)` or maybe even `tour.start(true)` to force it to start.

**Comment by benmarch** [comment]
Any update @vvillasoto?

**Comment by vvillasoto** [comment]
@benmarch I am able to make it work but not by using $scope.tour. This will not be found. I inspected it and found that the tour object is attached to any one of the step elements / or just the container element wherein all the steps can be found within the html. I used angular.element to access it from the controller.

```javascript
$scope.initTour = function() {
    // if you like to do any modification in the tour object
    angular.element( "#section1" ).scope().tour._options.template = "<div class='popover tour-xdkTour' role='tooltip'>" + "\n"
          + "<div class='arrow'></div>" + "\n" + "<h3 class='popover-title'></h3>" + "\n"
          + "<div class='popover-content'></div>" + "\n" + "<div class='popover-navigation'>"
          + "\n" + "<div class='btn-group'>" + "\n"
          + "<button class='btn btn-default' data-role='prev'>« Prev</button>" + "\n"
          + "<button class='btn btn-default' data-role='next'>Next »</button>" + "\n" + "</div>"
          + "\n" + "<button class='btn btn-default' data-role='end'>Next Widget</button>" + "\n"
          + "</div>" + "\n" + "</div>";
   // next you can init and start the tour
   angular.element( "#section1" ).scope().tour.init();
   angular.element( "#section1" ).scope().tour.start();
}

$scope.init = function() {
    MyService.getData().then(
        function(data) {
              $scope.data = data;
              $timeout($scope.initTour(), 2000);
        }
}

var interval = $interval($scope.init, 60000);

$scope.$on('$destroy', function() {
      $interval.cancel(interval);
});
```

hope this helps. Let me know if you figure out a better solution.

Thanks.

**Comment by benmarch** [comment]
It looks to me like this code is in a controller that is outside of the scope of the tour controller. If you can move this controller code inside of "#section1" then you would be able to access it via `$scope.tour`. You can also improve this by moving the template text into a [template script tag](https://docs.angularjs.org/api/ng/directive/script) and using the template-url attribute on the tour element.

**Comment by vvillasoto** [comment]
Thanks for the advice. Will try to improve on it. I think this is resolved :)
