### ISSUE TITLE
Not supporting the element attribute?

### ISSUE THREAD

**Issue by esoyke** [benmarch/angular-bootstrap-tour#38]
I want to highlight a nested element, is this possible? I am using angular datatables in my app and want to highlight the search input.

`<table id="myTable" datatable="ng" ...`

Datatables names this search input (tablename)_filter, so in bootstrap-tour I was able to highlight this input (I'm using backdrop) by configuring the step with what I knew the element's name would be:

`element: "#myTable_filter"`

I am trying to switch from bootstrap-tour to angular-bootstrap-tour because it is working better in my Angular SPA. But in angular-bootstrap-tour I can't seem to get this to work by including the same attribute

`<table id="myTable" datatable="ng" tour-step element: "#myTable_filter"...`

Likewise in bootstrap-tour I've been able to configure a nested element by looking for the first element of a given type such as:
`element: someElement > input:first-of-type`

**Comment by benmarch** [comment]
Right, with Bootstrap Tour you can do an imperative selection on the tour steps which is more inline with how jQuery works, but Angular prefers a declarative approach to selection via directives. I think we could add a feature that would allow you to select a descendant of the tour-step element, but I would first look into adding a tour-step to the element that you actually want to highlight (if made possible by angular datatables).
