### ISSUE TITLE
template-url is not working

### ISSUE THREAD

**Issue by dipteeR** [benmarch/angular-bootstrap-tour#39]
when I am adding new template its not working. I am getting error as 'elem.cloneNode is not a function' is not function. My template is very similar which you are using.

    <div class='popover tour'>
      <div class='arrow'></div>
      <h3 class='popover-title'></h3>
      <div class='popover-content'></div>
      <div class='popover-navigation'>
        <button class='btn btn-default' data-role='prev'>First</button>
        <span data-role='separator'>|</span>
        <button class='btn btn-default' data-role='next'>Last</button>
        <button class='btn btn-default' data-role='end'>End</button>
      </div>
    </div>

I am also getting same template in lookupTemplate as you mentioned. 

    XHR finished loading: GET "http://localhost:9000/views/tour_template.html".
    (anonymous function) @ angular.js:10765
    sendReq @ angular.js:10558
    serverRequest @ angular.js:10268
    processQueue @ angular.js:14792
    (anonymous function) @ angular.js:14808
    Scope.$eval @ angular.js:16052
    Scope.$digest @ angular.js:15870
    Scope.$apply @ angular.js:16160
    bootstrapApply @ angular.js:1679
    invoke @ angular.js:4523
    doBootstrap @ angular.js:1677
    bootstrap @ angular.js:1697
    angularInit @ angular.js:1591
    (anonymous function) @ angular.js:29013
    fire @ jquery.js:3099
    self.fireWith @ jquery.js:3211
    jQuery.extend.ready @ jquery.js:3417
    completed @ jquery.js:3433
    angular-bootstrap-tour.js:292 template us<div class='popover tour'>
      <div class='arrow'></div>
      <h3 class='popover-title'></h3>
      <div class='popover-content'></div>
      <div class='popover-navigation'>
        <button class='btn btn-default' data-role='prev'>First</button>
        <span data-role='separator'>|</span>
        <button class='btn btn-default' data-role='next'>Last</button>
        <button class='btn btn-default' data-role='end'>End</button>
      </div>
    </div>

**Comment by benmarch** [comment]
Can you paste in the stack trace of the "elem.cloneNode is not a function" error?

**Comment by benmarch** [comment]
Try updating to version 0.3.4-rc.2 and let me know if that works for you.

**Comment by benmarch** [comment]
Should be fixed as of 0.3.4. If not, please let me know. Thanks!
