### ISSUE TITLE
option attribute name collision

### ISSUE THREAD

**Issue by klmdb** [benmarch/angular-bootstrap-tour#4]
It might be usefull to require the tour options to be prefixed with 'bs-tour-' to avoid attribute collisions.

**Comment by benmarch** [comment]
Added this functionality to 0.3.0.

Use TourConfigProvider in you app's config block and set `prefixOptions` to `true` (see the readme for more info.) I used your suggestion of bsTour (will be bs-tour- as an attribute) as the default prefix if it is enabled.
