### ISSUE TITLE
Option to lock controls

### ISSUE THREAD

**Issue by vvillasoto** [benmarch/angular-bootstrap-tour#42]
Option to lock controls when tour is on.. (meaning user cannot do anything else but go through the tour) 

Is there such an option that can be configured? Possible to include?

Thanks

Kind Regards,
Vicente

**Comment by benmarch** [comment]
Hi Vicente,

I think that would be possible, but I don't think it would be worth building into this library. You can probably use the onStart and onEnd hooks to implement that sort of functionality in your app. If you would like to implement that in ABT and create a PR, I would gladly consider pulling it in.

Thank you for the suggestion,
Ben
