### ISSUE TITLE
starting tour from controller through ng-click is not working

### ISSUE THREAD

**Issue by rui7999** [benmarch/angular-bootstrap-tour#45]
//This is my controller for fraud-demo, when called it is calling the functions in bootstraptour.js rather than the angualr-bootstrap tour. How can i start the demo tour w.r.t angular-bootstrap tour

     $scope.steps = [
          {
              path:'/app/page1',
              element: "#tour1",
              title: "Title of my step",
              content: "content of the step",
              smartPlacement:true,
              placement:'left',
              orphan:true,
              reflex:true
          },
          {
              path:'/app/page2',
              element: "#tour-2",
              title: "Title of my step",
              content: "content of the step",
              placement:'right',
              autoScroll: true,
              smartPlacement:true,
              },
          {
              element: "#tour3,
              title: "Title of my step",
              content: "content of the step",
              smartPlacement:true,
              placement:'right',
              redirect: true,
          },

           $scope.tour =   new Tour({ //when hovered on 'Tour' it is displaying the function from bootstraptour.js
            storage: window.localStorage,
            backdrop: true,
            steps:$scope.steps,
            templateUrl:'app/demo.html'
         });

     $scope.showDemo = function (){ //this is the function i'm using for ng-click for a buttin link, ng-    click is working fine
           $scope.tour.init();
           $scope.tour.start();

       }

**Comment by benmarch** [comment]
Hey @rui7999, it looks like you are trying to use Bootstrap Tour directly. If you want to use Angular Bootstrap Tour, you have to add the attributes to the markup. Please see the README for instructions.

**Comment by rui7999** [comment]
Yes, i had already seen the Read me file .What you mean to say is i cant start the tour from controller? And i can only pass the attributes in directive only and what about the options do i need to pass every time in the directive?

**Comment by rui7999** [comment]
Why can't i start the tour from controller?

**Comment by benmarch** [comment]
You can start the tour from the controller, check out #36. 

The way you have it set up bypasses this library and just uses Bootstrap Tour. If you prefer setting up the tour the way you have it in you code snippit, i have to recommend that you do not use this library since it will just get in the way. You will still be able to use the Bootstrap Tour API within the Angular code in your app. If you are able to use the declarative syntax by adding the attributes, then i would have to recommend Angular UI Tour (my other library). This library is a simple wrapper around Bootstrap Tour that allows you to use directives instead of configs, so it might not be the right solution for you.

**Comment by rui7999** [comment]
Hmm Thanks for the explanation though, then i will use bootstrap tour itself. My only problem with it is i'm adding my own template and it doesn't work as below, Is there any better way that you know, please

template: "<div ng-include="'app/html'"></div>"

**Comment by benmarch** [comment]
Hey @rui7999 that probably isn't working because Bootstrap Tour won't compile the template for you. Your best bet might be to compile the template yourself and use it as the template:
```js
$http.get('app/html').then(function (response) {
    var template = $compile(response.data)(scope);
});

//or if it's in the template cache:

var template = $compile($templateCache.get('app/html'))(scope);
```

See how I do it here: https://github.com/benmarch/angular-bootstrap-tour/blob/master/app/tour_helpers.js#L36
