### ISSUE TITLE
How to autostart the tour ?

### ISSUE THREAD

**Issue by capic** [benmarch/angular-bootstrap-tour#6]
Hi, is it possible to autostart (depends to a condition) a tour without clicking on a button ?
Thanks

**Comment by benmarch** [comment]
Hey sorry for the delay... this can be done in a controller by interacting with the tour object on the scope when the controller loads. Would it be helpful to have an attribute that will evaluate to a boolean and start if true? I think that would be the only alternative.

**Comment by ll2585** [comment]
Can you give an example of this? Thanks!

**Comment by benmarch** [comment]
Something like this should work:

```html
<div tour>
    <div ng-controller="AutoStartController">
    </div>
</div>
```
```javascript
app.controller('AutoStartController", function ($scope) {
    var tourStarted = $scope.$watch('tour', function (tour) {
        if (tour) {
            tour.start(true);
            tourStarted();
        }
    });
});
```

**Comment by aendrew** [comment]
Confirming the above suggestion works.
