### ISSUE TITLE
Page doesn't get scroll if place the popup for the element at the bottom of the page

### ISSUE THREAD

**Issue by suriyagp** [benmarch/angular-bootstrap-tour#7]
A page contian several steps few things are place at the top or in middle. And two steps are placed at the bottom but On that particular step the page is not get scrolled it ramins at the top. But it works fine in bootstrap tour.

Is there any solution for this??

**Comment by benmarch** [comment]
Interesting, can you supply an example?

**Comment by suriyagp** [comment]
sure.. will provide a plnkr or fiddle link

**Comment by suriyagp** [comment]
is any file is added for to make that scrollable???
i added dependencies  bootstrap-tour.js, angular-tour.js but the scroll is not working

**Comment by benmarch** [comment]
Hey sorry for the delay... you shouldn't have to add any dependencies, but I don't think I can debug it without an example.

**Comment by benmarch** [comment]
Open for a year with no response from OP, closing...
