### ISSUE TITLE
template-url attribute shown in example doesn't work

### ISSUE THREAD

**Issue by HerbCaudill** [benmarch/angular-bootstrap-tour#8]
As far as I can tell, there's no reference in either angular-bootstrap-tour.js or bootstrap-tour.js to this attribute. I'd love it if this did work, though!

**Comment by HerbCaudill** [comment]
Never mind. This is supported. (I'm using $templateCache and was referencing the full URL path to the template instead of just the filename.)

**Comment by dchidrup** [comment]
@HerbCaudill Can you please explain with an example of this? We are stuck here. Please help!!!
